config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'pages#accueil'
  scope "(/:locale)", locale: /en/ do
    get '/:locale' => 'pages#accueil'
    # Nos services
    get '/services', to: 'pages#services', as: :services
    get '/services/strategie-digitale', to: 'pages#strategie_digitale', as: :strategie_digitale
    get '/services/web-developpement', to: 'pages#web_developpement', as: :web_developpement
    get '/services/community-management', to: 'pages#community_manager', as: :community_management
    get '/services/referencement', to: 'pages#referencement', as: :referencement

    get '/realisations', to: 'pages#portfolio', as: :portfolio
    get '/agence', to: 'pages#agence', as: :agence
    get '/contact', to: 'pages#contact', as: :contact
    post '/contact', to: 'pages#send_mail'
    get '/mentions_legales', to: 'pages#mentions_legales', as: :mentions_legales

    # optionel
    get '/social-wall', to: 'pages#social_wall', as: :social_wall

    resources :blogs

    # ADMINISTRATION #
    get '/admin', to: 'admins#accueil', as: :admin

    # NEWSLETTER #
    post '/', to: "newsletters#create"
    get '/desinscription', to: "newsletters#desinscription"
    delete '/desinscription', to: "newsletters#destroy"

    scope :admin do
      resources :users
      resources :categories
    end
  end


  # ckeditor

  mount Ckeditor::Engine => '/ckeditor'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
  extend FriendlyId
  friendly_id :titre, :use => :slugged

	mount_uploader :image, ImageBlogUploader
	before_validation :default_slug

	validates :image, presence: true, on: :create
	#validates :slug, format: {with: /\A[a-z0-9]\-]*\z/}

	belongs_to :categorie
	belongs_to :user, required: false, foreign_key: "users_id"

  private 

  	def default_slug
  		if !self.titre.empty? && self.slug.empty?
  			self.slug = titre.parameterize
  		end
  	end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :is_admin, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]


  # GET /blogs
  # GET /blogs.json
  def index
    @titre = t('blog.titre')
    @blogs = Blog.includes(:categorie).includes(:user).all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @titre = t('blog.titre')
    @premier = Blog.first.id
    @dernier = Blog.last.id
    @blogs = Blog.friendly_id.includes(:categorie).includes(:user).all
  end

  # GET /blogs/new
  def new
    @titre = t('blog.titre')
    @blog = Blog.new

  end

  # GET /blogs/1/edit
  def edit
    @titre = t('blog.titre')
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @titre = t('blog.titre')
    @blog = Blog.new(blog_params)
    @blog.id = Blog.last.id + 1
    @blog.users_id = current_user.id
    if @blog.save
      flash[:success] = t('blog.post_creer')
      redirect_to @blog
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    @titre = t('blog.titre')
    if @blog.update(blog_params)
      flash[:success] = t('blog.post_editer')
      redirect_to @blog
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    flash[:success] = t('blog.post_supprimer')
    redirect_to blogs_url
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:titre, :contenu, :categorie_id, :image, :image_legende, :slug, :user)
    end

    def is_admin
      redirect_to root_path if signed_in? && !current_user.is_admin?
    end

end

app/helpers/blogs_helper.rb
module BlogsHelper
	# Methode remove_tags #
	# Permet d'enlever les balises HTML #
	def remove_tags(content)
        doc = Nokogiri::HTML(content)
        doc.search('h1').xpath('text()').remove
        doc.search('h2').xpath('text()').remove
        doc.search('h3').xpath('text()').remove
        doc.search('h4').xpath('text()').remove
        doc.search('h5').xpath('text()').remove
        doc.search('ul').xpath('text()').remove
        doc.search('li').xpath('text()').remove
        doc.search('p').find_all.each do |p|
            p.remove if p.content.blank?
            p.remove if p.content.strip.empty?
        end
        doc = doc.to_html
	end
end

app/views/blogs/_form.html.erb
<%= form_for(blog) do |f| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titre %>
    <%= f.text_field :titre %>
  </div>

  <div class="field">
    <%= f.label :contenu %>
     <%= f.cktext_area :contenu, id: blog %>
  </div>

  <div class="field">
    <%= f.label :categorie %>
    <%= f.select :categorie_id, Categorie.pluck(:categorie_nom, :id) %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :image_legende %>
    <%= f.text_field :image_legende %>
  </div>
  
  <div class="field">
    <%= f.label :slug, "URL de l'article" %>
    <%= f.text_field :slug %>
  </div>
  <br />

  <div class="actions">
    <%= f.submit :Valider %>
  </div>
  <br />
<% end %>

app/views/blogs/edit.html.erb
<div class="bandeau_blog">
  <div class="col-sm-12 text-center">
    <h1>Editon des articles</h1>
  </div>
</div>

<div class="content portfolio">

<%= render 'form', blog: @blog %>

<%= link_to 'Aperçu', @blog %> |
<%= link_to "Retour à l'index", blogs_path %>

</div>

app/views/blogs/index.html.erb
<div class="bandeau_blog">
  <div class="col-sm-12 text-center">
    <h1><%= t('blog.headertitle') %></h1>
  </div>
</div>

<div class="content portfolio">

<p id="notice"><%= notice %></p>
<% if user_signed_in? && current_user.is_admin? %>
<span class="btn btn-default"><%= link_to 'Ecrire un nouveau post', new_blog_path %></span>
<% end %>
<br />

<div class="row col-centered">
  <% @blogs.reverse_each do |blog|%>
      <div class="col-sm-6 col-md-4 spacing">
        <div class="post col-centered">
          <img class="img-responsive" src="<%= blog.image %>" alt="<%= blog.image_legende %>">
          <div class="text_post col-centered">
            <h4><%= blog.titre.byteslice(0,20) %>...</h4>
            <p class="d_post">Posté le <%= blog.created_at.strftime('%d/%m/%Y') %></p>
            <!-- <p class="d_post">par <% if blog.user %><%= blog.user.firstname %> <%= blog.user.lastname %><% end %></p> -->
            <div class="contenu"><%= raw (sanitize remove_tags(blog.contenu), tags: %w(p)).truncate(250) %></div>
            <div class="sav_plus row col-centered">
              <div class="col-sm-4 col-centered">
                <form action="<%= blog_path(blog) %>">
                  <button class="btn btn-default" type="submit" value="<%= blog.titre %>"><%= t('blog.more') %></button>
                </form>
              </div>
              <% if user_signed_in? && current_user.is_admin? %>
              <div class="col-sm-4 col-centered">
                <form action="<%= edit_blog_path(blog) %>">
                  <button class="btn btn-info" type="submit" value="<%= blog.titre %>">Editer</button>
                </form>
              </div>
              <div class="col-sm-4 col-centered">
                <a href="<%= blog_path(blog) %>" data-confirm="Êtes-vous sûr?" data-method="delete"><button class="btn btn-danger"type="button" name="button">Suppr</button></a>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
  <% end %>

</div>
<br />
</div>

app/views/blogs/new.html.erb
<div class="bandeau_blog">
  <div class="col-sm-12 text-center">
    <h1>Ecrire un nouvel article</h1>
  </div>
</div>

<div class="content portfolio">

  <%= render 'form', blog: @blog %>

  <%= link_to "Retour à l'index", blogs_path %>

</div>

app/views/blogs/show.html.erb
<div class="bandeau_blog">
  <div class="col-sm-12 text-center">
    <h1><%= @blog.titre %></h1>
  </div>
</div>

<div class="content portfolio">

<p id="notice"><%= notice %></p>
<div class="row">

  <div class="col-sm-12 text-center">

    <% i = 0 %>
    <% list_id = [] %>
    <% @blogs.each do |blog| %>
      <% i = i + 1 %>
      <% list_id<<blog.slug %>
    <% end %>
    <% for j in 0..i-1 do %>
      <% if list_id[j] == @blog.slug %>
        <% prev = list_id[j-1] %>
        <% nex = list_id[j+1] %>
      <% end %>
    <% end %>

    <% if @blog.id > @premier %>
    <div class="nav-post">
      <a href="<%= blog_path(prev) %>"><i class="fa fa-arrow-circle-left" aria-hidden="true"></i></a>
    </div>
    <% end %>
    <div class="nav-post">
      <div class="blog_image">
        <img class="img-responsive center-block" src="<%= @blog.image %>" alt="<%= @blog.image_legende %>">
      </div>
  </div>
    <% if @blog.id < @dernier %>
    <div class="nav-post">
      <a href="<%= blog_path(nex) %>"><i class="fa fa-arrow-circle-right" aria-hidden="true"></i></a>
    </div>
    <% end %>
  </div>
</div>
<h6>
<% if @blog.categorie %>
  <U>Catégorie :</U> <%= @blog.categorie.categorie_nom %>
<% end %>
</h6>

<div class="row text-justify">
  <div class="col-sm-12">
    <div class="blog_content">
        <%= raw @blog.contenu %>
    </div>
  </div>
</div>
<div
  class="fb-like"
  data-share="true"
  data-width="450"
  data-show-faces="true">
</div>

<% if user_signed_in? && current_user.is_admin? %>
<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>
<% end %>
</div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/fr_FR/sdk.js#xfbml=1&version=v2.8&appId='1656043924700769'";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>