config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'pages#accueil'
  scope "(/:locale)", locale: /en/ do
    get '/:locale' => 'pages#accueil'
    # Nos services
    get '/services', to: 'pages#services', as: :services
    get '/services/strategie-digitale', to: 'pages#strategie_digitale', as: :strategie_digitale
    get '/services/web-developpement', to: 'pages#web_developpement', as: :web_developpement
    get '/services/community-management', to: 'pages#community_manager', as: :community_management
    get '/services/referencement', to: 'pages#referencement', as: :referencement

    get '/realisations', to: 'pages#portfolio', as: :portfolio
    get '/agence', to: 'pages#agence', as: :agence
    get '/contact', to: 'pages#contact', as: :contact
    post '/contact', to: 'pages#send_mail'
    get '/mentions_legales', to: 'pages#mentions_legales', as: :mentions_legales

    # optionel
    get '/social-wall', to: 'pages#social_wall', as: :social_wall

    resources :blogs

    # ADMINISTRATION #
    get '/admin', to: 'admins#accueil', as: :admin

    # NEWSLETTER #
    post '/', to: "newsletters#create"
    get '/desinscription', to: "newsletters#desinscription"
    delete '/desinscription', to: "newsletters#destroy"

    scope :admin do
      resources :users
      resources :categories
    end
  end


  # ckeditor

  mount Ckeditor::Engine => '/ckeditor'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/_map.html.erb
<div id="map"></div>
    <script>
      function initMap() {
        var artandteo = {lat: 48.132907, lng: -0.430239};
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 17,
          center: artandteo
        });
        //--> Configuration de l'icône personnalisée
        var image = {
            // Adresse de l'icône personnalisée
            url: 'img/gmark-AT.png',
            // Taille de l'icône personnalisée
            size: new google.maps.Size(30, 50),
            // Origine de l'image, souvent (0, 0)
            origin: new google.maps.Point(0,0),
            // L'ancre de l'image. Correspond au point de l'image que l'on raccroche à la carte. Par exemple, si votre îcone est un drapeau, cela correspond à son mâts
            anchor: new google.maps.Point(0, 40)
        };
        //--> Configuration de l'ombre personnalisée
        var shadow = {
            // Adresse de l'ombre personnalisée
            url: 'images/drapeau_ombre.png',
            // Taille de l'ombre personnalisée
            size: new google.maps.Size(32, 40),
            // Origine de l'image, souvent (0, 0)
            origin: new google.maps.Point(0,0),
            // L'ancre de l'image. Correspond au point de l'image que l'on raccroche à la carte. Par exemple, si votre îcone est un drapeau, cela correspond à son mâts
            anchor: new google.maps.Point(0, 40)
        };
        var marker = new google.maps.Marker({
          position: artandteo,
          map: map,
          title: "ArtandTeo",
          shadow: shadow,
          icon: image
        });
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCMXD2YYEMaEG_NQzkhOz3x8xkyxicY5Sw&callback=initMap">
    </script>

app/views/pages/accueil.html.erb
<section class="title-bar-home">
  <div class="nom_resume">
    <h1>ARTANDTEO</h1>
    <h5><%= t('accueil.creation_communication_digitale') %></h5>
  </div>
  <div class="slogan">
    <h2><%= t('accueil.slogan') %></h2>
  </div>
  <div class="row">
    <div class="col-md-3 col-md-offset-2 col-sm-3 col-sm-offset-2 text-center">
      <form action="<%= agence_path %>">
        <button type="submit" class="btn btn-default"><%= t('accueil.nous_trouver') %></button>
      </form>
    </div>
    <div class="col-md-3 col-md-offset-2 col-sm-3 text-center">
      <form action="<%= contact_path %>">
        <button type="submit" class="btn btn-info"><%= t('accueil.nous_contacter') %></button>
      </form>
    </div>
  </div>
</section>

<section class="tryptic">
  <div class="row">

      <div class="col-md-4 text-center">
        <a href="<%= strategie_digitale_path %>">
        <div class="tryptic_1">
          <h3><%= t('accueil.title_tryp1') %></h3>
          <i class="fa fa-plus-circle" aria-hidden="true"></i>
          <!-- <img src="/img/tryp1.png" alt="<%= t('accueil.alt_tryp1') %>"> -->
          <p><%= simple_format(t('accueil.texte_tryp1')) %></p>
        </div>
        </a>
      </div>

      <div class="col-md-4 text-center">
        <a href="<%= web_developpement_path %>">
        <div class="tryptic_2">
          <h3><%= t('accueil.title_tryp2') %></h3>
          <i class="fa fa-laptop" aria-hidden="true"></i>
          <!-- <img src="/img/tryp2.png" alt="<%= t('accueil.alt_tryp2') %>"> -->
          <p><%= simple_format(t('accueil.texte_tryp2')) %></p>
        </div>
        </a>
      </div>

      <div class="col-md-4 text-center">
        <a href="<%= referencement_path %>">
        <div class="tryptic_3">
          <h3><%= t('accueil.title_tryp3') %></h3>
          <i class="fa fa-sitemap" aria-hidden="true"></i>
          <!-- <img src="/img/tryp3.png" alt="<%= t('accueil.alt_tryp3') %>"> -->
          <p><%= simple_format(t('accueil.texte_tryp3')) %></p>
        </div>
        </a>
      </div>

  </div>
</section>

<!-- <section class="tryptic">
  <div class="row">
    <% for n in 1..3 do %>
      <div class="col-md-4 text-center">
        <div class="tryptic_<%= n %>">
          <h3><%= t('accueil.title_tryp' + n.to_s) %></h3>
          <img src="/img/tryp<%= n %>.png" alt="<%= t('accueil.alt_tryp' + n.to_s) %>">
          <hr>
          <p><%= t('accueil.texte_tryp' + n.to_s) %></p>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</section> -->

<section class="objectifs">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-md-offset-2 text-center">
      <h3><%= t('accueil.objectif') %></h3>
      <ul>
        <li>1 - <%= t('accueil.first') %></li>
        <li>2 - <%= t('accueil.second') %></li>
        <li>3 - <%= t('accueil.third') %></li>
      </ul>
      <br />
      <p>
        <%= t('accueil.txt_objectif') %>
      </p>
      <br />
    </div>
  </div>
</section>

<section class="besoin">
  <div class="row">
    <div class="col-md-6 col-md-offset-6">
      <div class="card_besoin">
        <h4><%= t('accueil.titre_visib') %></h4>
        <p><%= t('accueil.txt_visib') %></p>
        <div class="sav_plus">
          <form action="<%= strategie_digitale_path %>">
            <button type="submit" class="btn btn-default"><%= t('savoir_plus') %></button>
          </form>
        </div>
      </div>
      <div class="card_besoin">
        <h4><%= t('accueil.titre_besoin') %></h4>
        <p><%= t('accueil.txt_besoin1') %></p>
        <hr>
        <p><%= t('accueil.txt_besoin2') %></p>
        <div class="sav_plus">
          <form action="<%= web_developpement_path %>">
            <button type="submit" class="btn btn-default"><%= t('savoir_plus') %></button>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="last_posts">
  <div class="row">
    <div class="col-md-12 text-center">
      <h3><%= (t('accueil.titre_last_posts')) %></h3>
    </div>
  </div>
  <div class="row">
    <% @last_post.reverse_each do |post| %>
      <div class="col-md-6">
        <div class="post">
          <img class="img-responsive" src="<%= post.image %>" alt="<%= post.image_legende %>" />
          <div class="text_post">
            <h2><%= post.titre.byteslice(0,20) %>...</h2>
            <p class="d_post">Posté le <%= post.created_at.strftime('%d/%m/%Y') %></p>
            <div class="contenu">
            <%= raw (sanitize remove_tags(post.contenu), tags: %w(p)).truncate(250) %>
            </div>
            <div class="sav_plus">
              <form action="<%= blog_path(post) %>">
                <button type="submit" value="<%= post.titre %>" class="btn btn-default">Lire plus</button>
              </form>
            </div>
        </div>
        </div>
      </div>
    <% end %>
  </div>
</section>

<section class="nous_trouver">
  <div class="row">
    <div class="col-md-12 text-center">
      <h3><%= t('accueil.titre_nous_trouver') %></h3>
    </div>
  </div>
  <!-- <div class="map_google"></div> -->
  <div class="content">
      <%= render 'pages/map' %>
  </div>
</section>

<!-- <section class="passion">
  <div class="row">
    <div class="col-md-12 text-center">
      <h3><%= t('accueil.titre_passion') %></h3>
    </div>
  </div>
  <div class="row">
      <div class="col-md-6 text-center">
        <div class="contact_card">
          <img class="img-circle" src="/img/fred.jpg" alt="Photo de Fred">
          <hr>
          <h4><%= t('accueil.titre_fred') %></h4>
          <p><%= t('accueil.text_fred') %></p>
        </div>
      </div>
      <div class="col-md-6 text-center">
        <div class="contact_card">
          <img class="img-circle" src="/img/jp.jpg" alt="Photo de Jean-Pierre">
          <hr>
          <h4><%= t('accueil.titre_jp') %></h4>
          <p><%= t('accueil.text_jp') %></p>
        </div>
      </div>
  </div>
</section> -->

<section class="outils">
    <div class="row">
      <div class="col-md-12 text-center">
        <h3><%= t('accueil.titre_outils') %></h3>
      </div>
    </div>
    <div class="row logos_outils">
      <div class="col-md-6 text-right">
        <img src="/img/icons/logo_ruby.png" alt="logo Ruby">
        <img src="/img/icons/logo_rails.png" alt="logo Rails">
        <img src="/img/icons/logo_sketch.png" alt="logo Sketch Bohemian Coding">
        <img src="/img/icons/logo_atom.png" alt="logo Atom IDE">
      </div>
      <div class="col-md-6 text-left">
        <img src="/img/icons/logo_wordpress.png" alt="logo Wordpress">
        <img src="/img/icons/logo_drupal.png" alt="logo Drupal">
        <img src="/img/icons/logo_magento.png" alt="logo Magento e-commerce">
        <img src="/img/icons/logo_analytics.png" alt="logo Google Analytics">
      </div>
    </div>
</section>

<section class="inscrip_news">
  <div id="newsletter">
    <div class="row">
      <div class="col-md-12 text-center">
            <h3><%= t('inscrire_newsletter') %></h3>
      </div>
    </div>

    <div class="row">
      <%= form_for :newsletter do |f| %>
      <div class="col-md-3 col-md-offset-2">
          <%= f.text_field :name, class: "form-control", placeholder: t('votre_nom') %><br />
      </div>
      <div class="col-md-4">
          <%= f.email_field :email, class: "form-control", placeholder: t('votre_email') %><br />
      </div>
      <div class="col-md-1">
          <%= f.submit "Ok", class: "form-control btn-default" %>
      </div>
      <% end %>
    </div>
  </div>
</section>

app/views/pages/agence.html.erb
<div class="bandeau_contact">
  <div class="col-sm-12 text-center">
    <h1><%= t('agence.titre') %></h1>
  </div>
</div>

<div class="content">
  <div class="row text-center">
    <div class="col-sm-12 col-md-8 col-md-offset-2">
      <%= simple_format(t('agence.sous_titre')) %>
    </div>
  </div>

  <div class="row text-center">
    <div class="col-sm-12 col-md-8 col-md-offset-2">
      <%= simple_format(t('agence.content1')) %>
    </div>
  </div>

  <br />

  <div class="row text-center">
    <div class="col-sm-6 col-md-4 col-md-offset-2 legended">
      <div class="fondateur">
        <img class="img-circle" src="/img/fred.jpg" alt="Photo de Fred">
        <p><%= simple_format(t('agence.fred')) %></p>
      </div>
    </div>
    <div class="col-sm-6 col-md-4 legended">
      <div class="fondateur">
        <img class="img-circle" src="/img/jp.jpg" alt="Photo de Jean-Pierre">
        <p><%= simple_format(t('agence.j_p')) %></p>
      </div>
    </div>
  </div>

  <br /><br />

  <div class="row text-center">
    <div class="col-sm-12 col-md-8 col-md-offset-2">
      <%= simple_format(t('agence.sous_titre_2')) %>
    </div>
  </div>

  <div class="row text-center">
    <div class="col-sm-12 col-md-8 col-md-offset-2">
      <p><%= t('agence.content2') %></p>
    </div>
  </div>

  <div class="row text-center">
    <div class="col-sm-6 col-md-4 col-md-offset-2">
      <div class="partners">
        <%= simple_format(t('agence.partner1')) %>
      </div>
    </div>
    <div class="col-sm-6 col-md-4">
      <div class="partners">
        <%= simple_format(t('agence.partner2')) %>
      </div>
    </div>
    <div class="col-sm-6 col-md-4 col-md-offset-2">
      <div class="partners">
        <%= simple_format(t('agence.partner3')) %>
      </div>
    </div>
    <div class="col-sm-6 col-md-4">
      <div class="partners">
        <%= simple_format(t('agence.partner4')) %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12 text-center">
      <%= simple_format(t('agence.localisation')) %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-9 agencemap">
      <%= render 'pages/map' %>
    </div>
    <div class="col-md-3">
      <div class="adresse">
        <h4>ArtandTeo</h4>
        <p>3 rue de Beauregard</p>
        <p>53600 Châtres-la-Forêt</p>
        <p>tel: 02 43 69 24 27</p>
        <p>email: <a href="mailto:contact@artandteo.com">contact<%= icon('at') %>artandteo.com</a></p>
      </div>
    </div>
  </div>
  <br /><br />

</div>

app/views/pages/community_manager.erb
<h1><%= t('community_manager.titre') %></h1>

app/views/pages/contact.html.erb
<div class="bandeau_contact">
  <div class="col-sm-12 text-center">
    <h1><%= t('contact.titre') %></h1>
  </div>
</div>

<div class="content">
  <div class="row">
    <div class="col-sm-12 text-center">
      <p><%= simple_format(t('contact.content')) %></p>
    </div>
  </div>
  <br />
  <div class="row">
    <%= form_for :contact do |f| %>
      <div class="col-md-8 col-md-offset-2">
          <%= t('contact.nom') %>: <%= f.text_field :name, required: true, class: "form-control" %><br />
      </div>
      <div class="col-md-8 col-md-offset-2">
          <%= t('contact.email') %>: <%= f.email_field :email, required: true, class: "form-control" %><br />
      </div>
      <div class="col-md-8 col-md-offset-2">
          <%= t('contact.objet') %>: <%= f.text_field :objet, required: true, class: "form-control" %><br />
      </div>
      <div class="col-md-8 col-md-offset-2">
          <%= t('contact.message') %>: <%= f.text_area :message, required: true, class: "form-control" %><br />
      </div>
      <br />
      <div>
      <div class="col-md-8 col-md-offset-2">
          <p style="text-align: center;"><i><%= t('contact.mess') %><br /></i></p>
      </div>
      <div class="col-md-2 col-md-offset-5">
          <%= f.submit :Envoyer, value: t('contact.envoyer'), class: "form-control btn-default" %>
      </div>
    <% end %>
  </div>
  <br />
</div>

app/views/pages/mentions_legales.html.erb
<div class="bandeau_contact">
  <div class="col-sm-12 text-center">
    <h1><%= t('mlegales.titre') %></h1>
  </div>
</div>

<div class="content">
  <div class="row text-justify mentions">
    <div class="col-sm-12 col-md-8 col-md-offset-2 text-left">
      <p><%= simple_format(t('mlegales.content')) %></p>
    </div>
  </div>
  <br/>
</div>

app/views/pages/portfolio.html.erb
<div class="bandeau_titre">
  <div class="col-sm-12 text-center">
    <h1><%= t('realisations.titre') %></h1>
  </div>
</div>

<hr />

<div class="content portfolio">
<div class="row">
  <div class="col-sm-12 text-center">
    <p><%= t('realisations.sous_titre') %></p>
  </div>
</div>

<% for n in 1..5 do %>

<hr />

<div class="row">
  <div class="col-sm-12">
    <h4><%= t('realisations.nom_site_' + n.to_s) %></h4>
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    <p>Url : <a href="<%= t('realisations.url_' + n.to_s) %>" target="_blank"><%= t('realisations.url_' + n.to_s) %></a></p>
    <p><%= t('realisations.type_' + n.to_s) %></p>
    <p><%= t('realisations.content_' + n.to_s) %></p>
    <p><%= t('realisations.contentb_' + n.to_s) %></p>
  </div>
</div>
<br />
<div class="row">
  <div class="col-md-6 text-center">
    <a href="<%= t('realisations.url_' + n.to_s) %>" target="_blank"><img class="img-responsive aligncenter" src="<%= t('realisations.image_desk_' + n.to_s) %>" alt="<%= t('realisations.alt_desk_' + n.to_s) %>" width="350" height="248" /></a>
    <p style="text-align: center;"><%= t('realisations.leg_desk') %></p>
  </div>
  <div class="col-md-6 text-center">
    <a href="<%= t('realisations.url_' + n.to_s) %>" target="_blank"><img class="aligncenter wp-image-117 size-full" src="<%= t('realisations.image_mob_' + n.to_s) %>" alt="<%= t('realisations.alt_mob_' + n.to_s) %>" width="140" height="248" /></a>
    <p style="text-align: center;"><%= t('realisations.leg_mob') %></p>
  </div>
</div>

<% end %>

app/views/pages/referencement.html.erb
<div class="bandeau_contact">
  <div class="col-sm-12 text-center">
    <h1><%= t('referencement.titre') %></h1>
  </div>
</div>

<div class="content portfolio">
  <br />
  <hr>
  <br />
  <div class="row">
    <div class="col-sm-6 col-md-6">
      <div class="palette_ref">
        <p><%= simple_format(t('referencement.content1')) %></p>
      </div>
    </div>
    <div class="col-sm-6 col-md-6">
      <div class="palette_ref">
        <p><%= simple_format(t('referencement.content2')) %></p>
      </div>
    </div>
  </div>
  <br />
  <div class="row">
    <div class="col-sm-6 col-md-6">
      <div class="palette_ref">
        <p><%= simple_format(t('referencement.content3')) %></p>
      </div>
    </div>
    <div class="col-sm-6 col-md-6">
      <div class="palette_ref">
        <p><%= simple_format(t('referencement.content4')) %></p>
      </div>
    </div>
  </div>
  <br />
  <hr>
  <br />
  <div class="row">
    <div class="col-sm-5 col-md-4 col-md-offset-1">
      <div class="">
        <p><%= simple_format(t('referencement.content5')) %></p>
      </div>
    </div>
    <div class="col-sm-7 col-md-6">
      <p><%= simple_format(t('referencement.content6')) %></p>
    </div>
  </div>
    <br />
    <hr>
    <br />
</div>

app/views/pages/services.html.erb
<h1><%= t('services.titre') %></h1>

app/views/pages/social_wall.html.erb
<div class="bandeau_contact">
  <div class="col-sm-12 text-center">
    <h1><%= t('social.titre') %></h1>
  </div>
</div>

    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/fr_FR/sdk.js#xfbml=1&version=v2.8&appId='1656043924700769'";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

<script type="text/javascript">
function testAPI() {
    console.log('Welcome!  Fetching your information.... ');
    FB.api(
      '/artandteo/feed',
      'GET',
      {},
      function(response) {
              console.log(response);
      }
    );
  }
</script>


<div class="row text-center">

  <div class="col-sm-6">
    <div class="fb-post" data-href="https://www.facebook.com/artandteo/posts/1694713014172724:0" data-width="500" data-show-text="true">
      <blockquote cite="https://www.facebook.com/artandteo/posts/1694713014172724:0" class="fb-xfbml-parse-ignore">Publié par <a href="https://www.facebook.com/artandteo/">Facebook</a> sur&nbsp;<a href="https://www.facebook.com/artandteo/posts/1694713014172724:0">jeudi 27 août 2015</a>
      </blockquote>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="fb-post" data-href="https://www.facebook.com/artandteo/photos/a.1514062905571070.1073741828.1513740068936687/1698737037103655/?type=3" data-width="500" data-show-text="true">
      <blockquote cite="https://www.facebook.com/artandteo/photos/a.1514062905571070.1073741828.1513740068936687/1698737037103655/?type=3" class="fb-xfbml-parse-ignore">Publié par <a href="https://www.facebook.com/artandteo/">Facebook</a> sur&nbsp;<a href="https://www.facebook.com/artandteo/photos/a.1514062905571070.1073741828.1513740068936687/1698737037103655/?type=3">jeudi 27 août 2015</a>
      </blockquote>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="fb-post" data-href="https://www.facebook.com/artandteo/posts/1697003637276995:0" data-width="500" data-show-text="true">
      <blockquote cite="https://www.facebook.com/artandteo/posts/1697003637276995:0" class="fb-xfbml-parse-ignore">Publié par <a href="https://www.facebook.com/artandteo/">Facebook</a> sur&nbsp;<a href="https://www.facebook.com/artandteo/posts/1697003637276995:0">jeudi 27 août 2015</a>
      </blockquote>
    </div>
  </div>

</div>

<img src="" id="profileImage"/>

<div id="status">
</div>


<div
  class="fb-like"
  data-share="true"
  data-width="450"
  data-show-faces="true">
</div>

app/views/pages/strategie_digitale.html.erb
<div class="bandeau_stratdig">
  <div class="col-sm-12 text-center">
    <h1><%= t('strategie_digitale.titre') %></h1>
  </div>
</div>

<div class="content portfolio">
  <br />
  <hr>
  <br />
  <div class="row">
    <div class="col-sm-6 col-md-6">
      <div class="palette">
        <p><%= simple_format(t('strategie_digitale.content1')) %></p>
      </div>
    </div>
    <div class="col-sm-6 col-md-6">
      <div class="palette">
        <p><%= simple_format(t('strategie_digitale.content2')) %></p>
      </div>
    </div>
  </div>
  <br />
  <div class="row">
    <div class="col-sm-6 col-md-6">
      <div class="palette">
        <p><%= simple_format(t('strategie_digitale.content3')) %></p>
      </div>
    </div>
    <div class="col-sm-6 col-md-6">
      <div class="palette">
        <p><%= simple_format(t('strategie_digitale.content4')) %></p>
      </div>
    </div>
  </div>
  <br />
  <hr>
  <br />
  <div class="row">
    <div class="col-sm-5 col-md-4 col-md-offset-1">
      <div class="">
        <p><%= simple_format(t('strategie_digitale.content5')) %></p>
      </div>
    </div>
    <div class="col-sm-7 col-md-6">
      <p><%= simple_format(t('strategie_digitale.content6')) %></p>
    </div>
  </div>
    <br />
    <hr>
    <br />
</div>

app/views/pages/web_developpement.html.erb
<div class="bandeau_devweb">
  <div class="col-sm-12 text-center">
    <h1><%= t('web_developpement.titre') %></h1>
  </div>
</div>

<div class="content portfolio">
  <br />
  <hr>
  <br />
  <div class="row">
    <div class="col-sm-6 col-md-6">
      <div class="palette">
        <p><%= simple_format(t('web_developpement.content1')) %></p>
      </div>
    </div>
    <div class="col-sm-6 col-md-6">
      <div class="palette">
        <p><%= simple_format(t('web_developpement.content2')) %></p>
      </div>
    </div>
  </div>
  <br />
  <div class="row">
    <div class="col-sm-6 col-md-6">
      <div class="palette">
        <p><%= simple_format(t('web_developpement.content3')) %></p>
      </div>
    </div>
    <div class="col-sm-6 col-md-6">
      <div class="palette">
        <p><%= simple_format(t('web_developpement.content4')) %></p>
      </div>
    </div>
  </div>
  <br />
  <hr>
  <br />
  <div class="row">
    <div class="col-sm-12 col-md-8 col-md-offset-2">
      <p><%= simple_format(t('web_developpement.content5')) %></p>
    </div>
  </div>
    <br />
    <hr>
    <br />
</div>