config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'pages#accueil'
  scope "(/:locale)", locale: /en/ do
    get '/:locale' => 'pages#accueil'
    # Nos services
    get '/services', to: 'pages#services', as: :services
    get '/services/strategie-digitale', to: 'pages#strategie_digitale', as: :strategie_digitale
    get '/services/web-developpement', to: 'pages#web_developpement', as: :web_developpement
    get '/services/community-management', to: 'pages#community_manager', as: :community_management
    get '/services/referencement', to: 'pages#referencement', as: :referencement

    get '/realisations', to: 'pages#portfolio', as: :portfolio
    get '/agence', to: 'pages#agence', as: :agence
    get '/contact', to: 'pages#contact', as: :contact
    post '/contact', to: 'pages#send_mail'
    get '/mentions_legales', to: 'pages#mentions_legales', as: :mentions_legales

    # optionel
    get '/social-wall', to: 'pages#social_wall', as: :social_wall

    resources :blogs

    # ADMINISTRATION #
    get '/admin', to: 'admins#accueil', as: :admin

    # NEWSLETTER #
    post '/', to: "newsletters#create"
    get '/desinscription', to: "newsletters#desinscription"
    delete '/desinscription', to: "newsletters#destroy"

    scope :admin do
      resources :users
      resources :categories
    end
  end


  # ckeditor

  mount Ckeditor::Engine => '/ckeditor'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_Categorie, only: [:show, :edit, :update, :destroy]

  def index
    @titre = t('categorie.titre')
    @categories = Categorie.all
  end

  def show
    @titre = t('categorie.titre')
    @categorie = Categorie.includes(:blogs).find(params[:id])
  end

  # GET /categories/new
  def new
    @categorie = Categorie.new
  end

  # GET /categories/1/edit
  def edit
    @categorie = Categorie.find(params[:id])
  end

  def create

    @titre = t('categorie.titre')
    @categorie = Categorie.new(categorie_params)
    if @categorie.valid? 
       if @categorie.save
        flash[:success] = t('categorie.cat_creer')
        redirect_to @categorie
      end
    else 
      render 'edit'
    end
  end

  def update
    if @categorie.valid? 
      if @categorie.update(categorie_params)
        flash[:success] = t('categorie.cat_editer')
        redirect_to @categorie
      end
    else 
      redirect_to categories_path
    end
  end

  def destroy
    @categorie.destroy
    @categorie = Categorie.all
    flash[:success] = t('categorie.cat_supprimer')
    redirect_to categories_path
  end

  private
    def set_Categorie
      @categorie = Categorie.find(params[:id])
    end

    def categorie_params
      params.require(:categorie).permit(:categorie_nom)
    end
end

app/views/categories/_form.html.erb
<%= form_for(categorie) do |f| %>
	<div class="field">
	    <%= f.label :categorie_nom, t('categorie.nom') %>
	    <%= f.text_field :categorie_nom %>
  	</div>

  	<div class="actions">
    	<%= f.submit :Valider %>
  	</div>

<% end %>

app/views/categories/edit.html.erb
<h1><%= t('categorie.cat_nom') %></h1>

<%= render 'form', categorie: @categorie %>

app/views/categories/index.html.erb
<h1><%= t('categorie.titre') %></h1>

<table class="table table-striped">
	<thead>
		<tr>
			<td>#</td>	
			<td><%= t('categorie.cat_nom') %></td>
			<td>Actions</td>
		</tr>
	</thead>
	<tbody>
		<% @categories.each do |categorie| %>
		<tr>
			<td><%= categorie.id %></td>
			<td><%= categorie.categorie_nom %></td>
			<td>
				<a href="<%= edit_category_path(categorie) %>"><%= icon('edit') %></a>
				<a href="<%= category_path(categorie) %>" data-confirm="Sûr ?" data-method="delete"><%= icon('remove') %></a>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>

<a href="<%= new_category_path %>"><button class="btn btn-info"><%= t('categorie.btn-creer') %></button></a>

app/views/categories/new.html.erb
<h1><%= t('categorie.btn-creer') %></h1>

<div class="content">
<%= render 'form', categorie: @categorie %>
</div>

app/views/categories/show.html.erb
<h1><%= t('categorie.afficher') %> : <%= @categorie.categorie_nom %></h1>

<% @categorie.blogs.each do |blog| %>
	<div class="col-sm-4 spacing">
        <div class="post col-centered">
          <img class="img-responsive" src="<%= blog.image %>" alt="<%= blog.image_legende %>">
          <div class="text_post col-centered">
            <h2><%= blog.titre.byteslice(0,20) %>...</h2>
            <p class="d_post">Posté le <%= blog.created_at.strftime('%d/%m/%Y à %H:%M') %> dans <% if blog.categorie %><%= blog.categorie.categorie_nom %><% end %></p>
            <div class="contenu"><%= raw (sanitize remove_tags(blog.contenu), tags: %w(p)).truncate(250) %></div>
            <div class="sav_plus row col-centered">
              <div class="col-sm-4 col-centered">
                <form action="<%= blog_path(blog) %>">
                  <button class="btn btn-default" type="submit" value="<%= blog.titre %>">Lire plus</button>
                </form>
              </div>
              <% if user_signed_in? && current_user.is_admin? %>
              <div class="col-sm-4 col-centered">
                <%= link_to 'Editer', edit_blog_path(blog), class: "btn btn-primary" %>
              </div>
              <div class="col-sm-4 col-centered">
                <%= link_to 'Suppr', blog, method: :delete, data: { confirm: 'Êtes-vous sûr?' }, class: "btn btn-danger" %>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
<% end %>