config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'pages#accueil'
  scope "(/:locale)", locale: /en/ do
    get '/:locale' => 'pages#accueil'
    # Nos services
    get '/services', to: 'pages#services', as: :services
    get '/services/strategie-digitale', to: 'pages#strategie_digitale', as: :strategie_digitale
    get '/services/web-developpement', to: 'pages#web_developpement', as: :web_developpement
    get '/services/community-management', to: 'pages#community_manager', as: :community_management
    get '/services/referencement', to: 'pages#referencement', as: :referencement

    get '/realisations', to: 'pages#portfolio', as: :portfolio
    get '/agence', to: 'pages#agence', as: :agence
    get '/contact', to: 'pages#contact', as: :contact
    post '/contact', to: 'pages#send_mail'
    get '/mentions_legales', to: 'pages#mentions_legales', as: :mentions_legales

    # optionel
    get '/social-wall', to: 'pages#social_wall', as: :social_wall

    resources :blogs

    # ADMINISTRATION #
    get '/admin', to: 'admins#accueil', as: :admin

    # NEWSLETTER #
    post '/', to: "newsletters#create"
    get '/desinscription', to: "newsletters#desinscription"
    delete '/desinscription', to: "newsletters#destroy"

    scope :admin do
      resources :users
      resources :categories
    end
  end


  # ckeditor

  mount Ckeditor::Engine => '/ckeditor'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer>

  <div id="social-footer">
    <div class="row">
    <div class="col-md-12 text-center">
        <span>
          <a href="https://www.facebook.com/artandteo/?fref=ts" target="_blank" alt="Facebook ArtandTeo"><img src="/img/icons/fb.png" alt="Facebook ArtandTeo"></a>
          <a href="https://www.linkedin.com/in/frédéric-reubrecht-2aba76107?trk=nav_responsive_tab_profile" target="_blank" alt="Linkedin ArtandTeo"><img src="/img/icons/lk.png" alt="Linkedin ArtandTeo"></a>
          <a href="https://twitter.com/artandteo" target="_blank" alt="Twitter ArtandTeo"><img src="/img/icons/tw.png" alt="Twitter"></a>
          <a href="https://plus.google.com/u/0/103348544084626253437" target="_blank" alt="Google+ ArtandTeo"><img src="/img/icons/gp.png" alt="Google+ ArtandTeo"></a>
        </span>
      </div>
    </div>
  </div>

  <div id="menu-footer">
    <div class="row">
      <div class="col-md-3">
        <a href="<%= mentions_legales_path %>"><%= t('mlegales.titre') %></a>
      </div>
      <div class="col-md-3">
        <a href="<%= social_wall_path %>"><%= t('social_wall') %></a>
      </div>
      <div class="col-md-3">
        <% if user_signed_in? %>
        <a href="<%= destroy_user_session_path %>" alt="<% t('deconnexion') %>" data-method="delete"><%= t('deconnexion') %></a>
        <% else %>
        <a href="<%= new_user_session_path %>" alt="<% t('connexion') %>"><%= t('connexion') %></a>
        <% end %>
      </div>
      <div class="col-md-3">
        <a href=""><%= t('tous_droits_reserves') %></a>
      </div>
    </div>
  </div>

</footer>

app/views/layouts/_header.html.erb
<header>
  <%=javascript_tag "window.locale = #{I18n.locale.to_s.inspect};" %>
  <div class="top-bar">
    <div class="social-lang">
      <span class="socials-icon">
        <a href="https://www.facebook.com/artandteo/?fref=ts" target="_blank" alt="Facebook ArtandTeo"><img src="/img/icons/fb.png" alt="Facebook ArtandTeo"></a>
        <a href="https://www.linkedin.com/in/frédéric-reubrecht-2aba76107?trk=nav_responsive_tab_profile" target="_blank" alt="Linkedin ArtandTeo"><img src="/img/icons/lk.png" alt="Linkedin ArtandTeo"></a>
        <a href="https://twitter.com/artandteo" target="_blank" alt="Twitter"><img src="/img/icons/tw.png" alt="Twitter"></a>
        <a href="https://plus.google.com/u/0/103348544084626253437" target="_blank" alt="Google+ ArtandTeo"><img src="/img/icons/gp.png" alt="Google+ ArtandTeo"></a>
      </span>
      <span class="languages">
        <a href="/" alt="Définir la langue du site en français"><img class="lg-sel" src="/img/icons/flag_france.png" title="Français"/></a>
        <a href="/en<%= request.path %>" alt="Définir la langue du site en anglais"><img class="lg-unsel" src="/img/icons/flag_uk.png" title="Anglais"></a>
      </span>
    </div>

    <div class="contacts">
      <a href="mailto:contact@artandteo.com"><div class="icontb"><%= icon('envelope') %></div><div class="txttb">contact<%= icon('at') %>artandteo.com</div></a>
      <!-- <a href="tel:+33243692427"><div class="icontb"><%= icon('mobile') %></div><div class="txttb">02 43 69 24 27</div></a> -->
    </div>
  </div>

  <nav class="navbar navbar-default">
   <div class="container-fluid">
     <!-- Brand and toggle get grouped for better mobile display -->
     <div class="navbar-header">
       <a class="logo_collapsed" href="<%= root_path %>">
         <img alt="Logo ArtandTeo" src="/img/logfb-ArtandTeo.png">
       </a>
       <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </button>
     </div>

     <!-- Collect the nav links, forms, and other content for toggling -->
     <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
       <div id="menu" class="row">

         <div id="left-menu" class="col-sm-5 text-center">
           <ul class="nav navbar-nav navbar-right">
             <li><a href="<%= root_path %>"><%= t('liens.accueil') %> <span class="sr-only">(current)</span></a></li>
             <li><a class="separator"></a></li>
             <li><a href="<%= agence_path %>"><%= t('liens.agence') %></a></li>
             <li><a class="separator"></a></li>
             <li class="dropdown">
               <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Services <span class="caret"></span></a>
               <ul class="dropdown-menu">
                 <li><a href="<%= strategie_digitale_path %>"><%= t('liens.strategie_digitale') %></a></li>
                 <li><a href="<%= web_developpement_path %>"><%= t('liens.web_developpement') %></a></li>
                 <!-- <li><a href="<%= community_management_path %>"><%= t('liens.community_manager') %></a></li> -->
                 <li><a href="<%= referencement_path %>"><%= t('liens.referencement') %></a></li>
               </ul>
             </li>
           </ul>
         </div>

         <div id="logo_at" class="col-sm-2 text-center">
           <a class="" href="<%= root_path %>">
             <img alt="Logo ArtandTeo" src="/img/logfb-ArtandTeo.png">
           </a>
         </div>

         <div id= "right-menu" class="col-sm-5 text-center">
           <ul class="nav navbar-nav">
             <li><a href="<%= portfolio_path %>"><%= t('liens.realisations') %></a></li>
             <li><a class="separator"></a></li>
             <li><a href="<%= blogs_path %>"><%= t('liens.blog') %></a></li>
             <li><a class="separator"></a></li>
             <li><a href="<%= contact_path %>"><%= t('liens.contact') %></a></li>
           </ul>
         </div>

       </div>
     </div><!-- /.navbar-collapse -->
   </div><!-- /.container-fluid -->
  </nav>

<!--               Navbar fixed                 -->

  <nav class="navbar_fixed">
  <div class="navbar navbar-default">

   <div class="container-fluid">
     <!-- Brand and toggle get grouped for better mobile display -->
     <div class="navbar-header">
       <a class="logo_collapsed" href="<%= root_path %>">
         <img alt="Logo ArtandTeo" src="/img/logfb-ArtandTeo.png">
       </a>
       <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2" aria-expanded="false">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </button>
     </div>

     <!-- Collect the nav links, forms, and other content for toggling -->
     <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
       <div id="menu" class="row">

         <div id="left-menu" class="col-sm-5 text-center">
           <ul class="nav navbar-nav navbar-right">
             <li><a href="<%= root_path %>"><%= t('liens.accueil') %> <span class="sr-only">(current)</span></a></li>
             <li><a class="separator"></a></li>
             <li><a href="<%= agence_path %>"><%= t('liens.agence') %></a></li>
             <li><a class="separator"></a></li>
             <li class="dropdown">
               <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Services <span class="caret"></span></a>
               <ul class="dropdown-menu">
                 <li><a href="<%= strategie_digitale_path %>"><%= t('liens.strategie_digitale') %></a></li>
                 <li><a href="<%= web_developpement_path %>"><%= t('liens.web_developpement') %></a></li>
                 <!-- <li><a href="<%= community_management_path %>"><%= t('liens.community_manager') %></a></li> -->
                 <li><a href="<%= referencement_path %>"><%= t('liens.referencement') %></a></li>
               </ul>
             </li>
           </ul>
         </div>

         <div id="logo_at" class="col-sm-2 text-center">
           <a class="" href="<%= root_path %>">
             <img alt="Logo ArtandTeo" src="/img/logfb-ArtandTeo.png">
           </a>
         </div>

         <div id= "right-menu" class="col-sm-5 text-center">
           <ul class="nav navbar-nav">
             <li><a href="<%= portfolio_path %>"><%= t('liens.realisations') %></a></li>
             <li><a class="separator"></a></li>
             <li><a href="<%= blogs_path %>"><%= t('blog.titre') %></a></li>
             <li><a class="separator"></a></li>
             <li><a href="<%= contact_path %>"><%= t('liens.contact') %></a></li>
           </ul>
         </div>

       </div>
     </div><!-- /.navbar-collapse -->
   </div><!-- /.container-fluid -->
   </div>
  </nav>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr" xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ArtandTeo | <%= @titre %></title>

    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= image_url(meta_image) %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META['twitter_account'] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META['twitter_account'] %>">
    <meta name="twitter:image:src" content="<%= image_url(meta_image) %>">

    <!-- Google+ Schema.org markup -->
    <meta itemprop="name" content="<%= meta_title %>">
    <meta itemprop="description" content="<%= meta_description %>">
    <meta itemprop="image" content="<%= image_url(meta_image) %>">

    <%= csrf_meta_tags %>
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Rajdhani|Rubik+One" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css" />
    <script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js"></script>
    <script>
      document.addEventListener("turbolinks:load", function() {
      window.cookieconsent.initialise({
        "theme": "edgeless",
        "static": "true",
        "palette": {
          "popup": {
            "background": "rgba(0, 0, 0, 0.5)"
          },
          "button": {
            "background": "#F8931D"
          }
        },
        "content": {
          "message": "Nous utilisons des cookies pour vous garantir la meilleure expérience sur notre site. Si vous continuez à utiliser ce dernier, nous considérerons que vous acceptez l'utilisation des cookies. ",
          "dismiss": "Ok",
          "link": "En savoir plus",
          "href": "http://www.artandteo.com/mentions_legales"
        }
      })});
      </script>

  </head>

  <body>
    <%= render 'layouts/header' %>


    <div class="container">
       <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>" style="margin-top: 7px"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>-->

<!-- Initialisation SDK Facebook -->
    <script>
      window.fbAsyncInit = function() {
        FB.init({
          appId      : '1656043924700769',
          xfbml      : true,
          version    : 'v2.8'
        });

        FB.AppEvents.logPageView();
        FB.getLoginStatus(function(response) {
          if (response.status === 'connected') {
            console.log('Logged in.');
          }
          else {
            FB.login();
          }
        });
      };
    </script>

  </body>
</html>